  # total subject where organism growth was found (+ results available after discharge)
WITH
  MB_positive AS (
  SELECT
    --- get cohort information
    co.SUBJECT_ID,
    co.HADM_ID,
    co.ADMITTIME,
    co.DISCHTIME,
    co.ICUSTAY_ID,
    co.INTIME,
    co.OUTTIME,
    co.LOS_ICU,
    co.AGE_ADMISSION
    --- get microbiology information
    ,
    me.SPEC_TYPE_DESC,
    me.ORG_ITEMID,
    me.ORG_NAME,
    me.CHARTDATE
  FROM
    `mimic-267216.CohorSelection_Pneumonia.1_First_query` AS co
  INNER JOIN
    `physionet-data.mimiciii_clinical.microbiologyevents` AS me
  ON
    co.SUBJECT_ID = me.SUBJECT_ID
    AND co.HADM_ID = me.HADM_ID
    AND me.ORG_NAME IS NOT NULL
  GROUP BY
    co.SUBJECT_ID,
    co.HADM_ID,
    co.ADMITTIME,
    co.DISCHTIME,
    co.ICUSTAY_ID,
    co.INTIME,
    co.OUTTIME,
    co.LOS_ICU,
    co.AGE_ADMISSION,
    me.SPEC_TYPE_DESC,
    me.ORG_ITEMID,
    me.ORG_NAME,
    me.CHARTDATE )
  #  this query gets all subject ids with negative microbiology events exclunding stool test
  ,
  BM_negative AS (
  SELECT
    --- get cohort information
    co.SUBJECT_ID,
    co.HADM_ID,
    co.ADMITTIME,
    co.DISCHTIME,
    co.ICUSTAY_ID,
    co.INTIME,
    co.OUTTIME,
    co.LOS_ICU,
    co.AGE_ADMISSION
    --- get microbiology information
    ,
    me.SPEC_TYPE_DESC,
    me.ORG_ITEMID,
    me.ORG_NAME,
    me.CHARTDATE
  FROM
    `mimic-267216.CohorSelection_Pneumonia.1_First_query` AS co
  INNER JOIN
    `physionet-data.mimiciii_clinical.microbiologyevents` AS me
  ON
    co.SUBJECT_ID = me.SUBJECT_ID
    AND co.HADM_ID = me.HADM_ID
    AND me.ORG_NAME IS NULL
    AND SPEC_TYPE_DESC != 'STOOL'
  GROUP BY
    co.SUBJECT_ID,
    co.HADM_ID,
    co.ADMITTIME,
    co.DISCHTIME,
    co.ICUSTAY_ID,
    co.INTIME,
    co.OUTTIME,
    co.LOS_ICU,
    co.AGE_ADMISSION,
    me.SPEC_TYPE_DESC,
    me.ORG_ITEMID,
    me.ORG_NAME,
    me.CHARTDATE
  ORDER BY
    co.SUBJECT_ID ),
  combined AS (
  SELECT
    CASE
      WHEN (Growth.ORG_NAME IS NOT NULL) THEN Growth.SUBJECT_ID
    ELSE
    noGrowth.SUBJECT_ID
  END
    AS SUBJECT_ID,
    CASE
      WHEN (Growth.ORG_NAME IS NOT NULL) THEN Growth.HADM_ID
    ELSE
    noGrowth.HADM_ID
  END
    AS HADM_ID,
    CASE
      WHEN (Growth.ORG_NAME IS NOT NULL) THEN Growth.ICUSTAY_ID
    ELSE
    noGrowth.ICUSTAY_ID
  END
    AS ICUSTAY_ID,
    CASE
      WHEN (Growth.ORG_NAME IS NOT NULL) THEN Growth.SPEC_TYPE_DESC
    ELSE
    noGrowth.SPEC_TYPE_DESC
  END
    AS SPEC_TYPE_DESC,
    CASE
      WHEN (Growth.ORG_NAME IS NOT NULL) THEN Growth.ORG_NAME
    ELSE
    noGrowth.ORG_NAME
  END
    AS ORG_NAME
  FROM
    BM_negative AS noGrowth
  FULL OUTER JOIN
    MB_positive AS Growth
  ON
    noGrowth.SUBJECT_ID = Growth.SUBJECT_ID),
  step1 AS (
  SELECT
    SUBJECT_ID,
    HADM_ID,
    ICUSTAY_ID,
    SPEC_TYPE_DESC,
    ORG_NAME
  FROM
    combined AS c
  WHERE
    c.ORG_NAME IS NULL )
  # Classify infected patinets
  ,
  classifiedGroup AS (
  SELECT
    me.SUBJECT_ID,
    me.HADM_ID,
    me.ICUSTAY_ID,
    me.SPEC_TYPE_DESC,
    me.ORG_NAME,
    CASE
      WHEN me.ORG_NAME IN ( 'ACHROMOBACTER (ALCALIGENES) DENTRIFICANS', 'ACIDFAST BACILLI', 'ACINETOBACTER BAUMANNII', 'ACINETOBACTER BAUMANNII COMPLEX', 'AEROCOCCUS SPECIES', 'AEROCOCCUS VIRIDANS', 'AFB GROWN IN CULTURE; ADDITIONAL INFORMATION TO FOLLOW', 'ALCALIGENES (ACHROMOBACTER) SPECIES', 'ALCALIGENES XYLOSOXIDANS', 'ALPHA STREPTOCOCCI', 'ANAEROBIC GRAM NEGATIVE ROD(S)', 'ANAEROBIC GRAM POSITIVE COCCUS(I)', 'ANAEROBIC GRAM POSITIVE ROD(S)', 'BACILLUS SPECIES', 'BACILLUS SPECIES; NOT ANTHRACIS', 'BACTERIA', 'BACTEROIDES FRAGILIS', 'BACTEROIDES FRAGILIS GROUP', 'BACTEROIDES UREOLYTICUS GROUP', 'BETA STREPTOCOCCI, NOT GROUP A', 'BETA STREPTOCOCCUS', 'BETA STREPTOCOCCUS GROUP A', 'BETA STREPTOCOCCUS GROUP B', 'BETA STREPTOCOCCUS GROUP C', 'BETA STREPTOCOCCUS GROUP G', 'BETA STREPTOCOCCUS NOT GROUP A OR B', 'BORDETELLA SPECIES', 'BURKHOLDERIA (PSEUDOMONAS) CEPACIA', 'BURKHOLDERIA CEPACIA GROUP', 'BURKHOLDERIA SPECIES', 'CAMPYLOBACTER SPECIES', 'CAPNOCYTOPHAGA SPECIES', 'CITROBACTER AMALONATICUS', 'CITROBACTER FREUNDII COMPLEX', 'CITROBACTER KOSERI', 'CITROBACTER SPECIES', 'CITROBACTER YOUNGAE', 'CLOSTRIDIUM DIFFICILE', 'CLOSTRIDIUM PERFRINGENS', 'CLOSTRIDIUM SPECIES', 'CLOSTRIDIUM SPECIES NOT C. PERFRINGENS OR C. SEPTICUM', 'CORYNEBACTERIUM SPECIES (DIPHTHEROIDS)', 'CORYNEBACTERIUM STRIATUM', 'CORYNEBACTERIUM UREALYTICUM SP. NOV.', 'CORYNEBCATERIUM AMYCOLATUM', 'EIKENELLA CORRODENS', 'EIKENELLA CORRODENS', 'ENTEROBACTER AEROGENES', 'ENTEROBACTER ASBURIAE', 'ENTEROBACTER CLOACAE', 'ENTEROBACTER CLOACAE COMPLEX', 'ENTEROBACTER SAKAZAKII', 'ENTEROBACTER SPECIES', 'ENTEROBACTERIACEAE', 'ENTEROCOCCUS FAECALIS', 'ENTEROCOCCUS FAECIUM', 'ENTEROCOCCUS GALLINARUM', 'ENTEROCOCCUS RAFFINOSUS', 'ENTEROCOCCUS SP.', 'ESCHERICHIA COLI', 'FUSOBACTERIUM NUCLEATUM', 'FUSOBACTERIUM SPECIES', 'GAMMA(I.E. NON-HEMOLYTIC) STREPTOCOCCUS', 'GEMELLA SPECIES', 'GRAM NEGATIVE COCCI', 'GRAM NEGATIVE DIPLOCOCCI', 'GRAM NEGATIVE ROD #1', 'GRAM NEGATIVE ROD #2', 'GRAM NEGATIVE ROD #3', 'GRAM NEGATIVE ROD #4', 'GRAM NEGATIVE ROD(S)', 'GRAM POSITIVE BACTERIA', 'GRAM POSITIVE COCCUS(COCCI)', 'GRAM POSITIVE RODS', 'HAEMOPHILUS INFLUENZAE', 'HAEMOPHILUS INFLUENZAE, BETA-LACTAMASE NEGATIVE', 'HAEMOPHILUS INFLUENZAE, BETA-LACTAMASE POSITIVE', 'HAEMOPHILUS PARAINFLUENZAE', 'HAEMOPHILUS SP', 'HAEMOPHILUS SPECIES NOT INFLUENZAE', 'HAFNIA ALVEI', 'KLEBSIELLA OXYTOCA', 'KLEBSIELLA PNEUMONIAE', 'KLEBSIELLA SPECIES', 'LACTOBACILLUS SPECIES', 'LEGIONELLA PNEUMOPHILA', 'LEGIONELLA SPECIES', 'LEUCONOSTOC SPECIES', 'LISTERIA MONOCYTOGENES', 'MICROCOCCUS/STOMATOCOCCUS SPECIES', 'MORAXELLA (BRANHAMELLA) CATARRHALIS', 'MORAXELLA CATARRHALIS', 'MORAXELLA CATARRHALIS, PRESUMPTIVE IDENTIFICATION', 'MORAXELLA OSLOENSIS', 'MORGANELLA MORGANII', 'MYCOBACTERIUM ABSCESSUS', 'MYCOBACTERIUM AVIUM COMPLEX', 'MYCOBACTERIUM GORDONAE', 'MYCOBACTERIUM TUBERCULOSIS', 'MYCOBACTERIUM TUBERCULOSIS COMPLEX', 'NEISSERIA MENINGITIDIS', 'NEISSERIA SPECIES', 'NOCARDIA ASTEROIDES COMPLEX', 'NOCARDIA SPECIES', 'NON-FERMENTER, NOT PSEUDOMONAS AERUGINOSA', 'NUTRITIONALLY VARIANT STREPTOCOCCUS', 'PANTOEA (ENTEROBACTER) AGGLOMERANS', 'PANTOEA SPECIES', 'PASTEURELLA MULTOCIDA', 'PASTEURELLA SPECIES', 'POSITIVE FOR GROUP B BETA STREP', 'POSITIVE FOR M. TUBERCULOSIS BY MTD', 'POSITIVE FOR METHICILLIN RESISTANT STAPH AUREUS', 'POSITIVE FOR UREAPLASMA UREALYTICUM', 'PRESUMPTIVE CLOSTRIDIUM PERFRINGENS', 'PRESUMPTIVE CLOSTRIDIUM SEPTICUM', 'PRESUMPTIVE FUSOBACTERIUM MORTIFERUM/VARIUM GROUP', 'PRESUMPTIVE GARDNERELLA VAGINALIS', 'PRESUMPTIVE MORAXELLA CATARRHALIS', 'PRESUMPTIVE PEPTOSTREPTOCOCCUS SPECIES', 'PRESUMPTIVE PROPIONIBACTERIUM ACNES', 'PRESUMPTIVE STREPTOCOCCUS BOVIS', 'PRESUMPTIVE VEILLONELLA SPECIES', 'PREVOTELLA SPECIES', 'PROBABLE ENTEROCOCCUS', 'PROBABLE GARDNERELLA VAGINALIS', 'PROBABLE MICROCOCCUS SPECIES', 'PROPIONIBACTERIUM ACNES', 'PROPIONIBACTERIUM SPECIES', 'PROTEUS MIRABILIS', 'PROTEUS SPECIES', 'PROTEUS VULGARIS', 'PROTEUS VULGARIS GROUP', 'PROVIDENCIA RETTGERI', 'PROVIDENCIA STUARTII', 'PSEUDOMONAS AERUGINOSA', 'PSEUDOMONAS FLUORESCENS', 'PSEUDOMONAS SPECIES', 'PSEUDOMONAS STUTZERI', 'RESEMBLING MICROCOCCUS/STOMATOCOCCUS SPECIES', 'ROTHIA (STOMATOCOCCUS) MUCILAGINOSA', 'SALMONELLA SPECIES', 'SERRATIA LIQUEFACIENS', 'SERRATIA MARCESCENS', 'SERRATIA SPECIES', 'STAPH AUREUS COAG +', 'STAPHYLOCOCCUS EPIDERMIDIS', 'STAPHYLOCOCCUS HOMINIS', 'STAPHYLOCOCCUS LUGDUNENSIS', 'STAPHYLOCOCCUS SPECIES', 'STAPHYLOCOCCUS, COAGULASE NEGATIVE', 'STAPHYLOCOCCUS, COAGULASE NEGATIVE, PRESUMPTIVELY NOT S. SAPROPHYTICUS', 'STENOTROPHOMONAS (XANTHOMONAS) MALTOPHILIA', 'STREPTOCOCCUS ANGINOSUS', 'STREPTOCOCCUS ANGINOSUS (MILLERI) GROUP', 'STREPTOCOCCUS BOVIS', 'STREPTOCOCCUS MILLERI', 'STREPTOCOCCUS MILLERI GROUP', 'STREPTOCOCCUS MITIS', 'STREPTOCOCCUS PNEUMONIAE', 'STREPTOCOCCUS SPECIES', 'VIBRIO SPECIES', 'VIRIDANS STREPTOCOCCI', 'porphyromonas', 'ESCHERICHIA FERGUSONII' ) THEN 'Bacteria'
      WHEN me.ORG_NAME IN ( 'ADENOVIRUS',
      'CYTOMEGALOVIRUS',
      'HERPES SIMPLEX VIRUS TYPE 1',
      'HERPES SIMPLEX VIRUS TYPE 2',
      'VIRUS',
      '%Virus%',
      '%VIRUS%',
      'INFLUENZA A VIRUS',
      'INFLUENZA B VIRUS',
      'PARAINFLUENZA VIRUS TYPE 1',
      'PARAINFLUENZA VIRUS TYPE 3',
      'POSITIVE FOR ADENOVIRUS',
      'POSITIVE FOR CYTOMEGALOVIRUS',
      'cytomegalovirus',
      'POSITIVE FOR HERPES SIMPLEX TYPE 1 (HSV1)',
      'POSITIVE FOR HERPES SIMPLEX TYPE 2 (HSV2)',
      'POSITIVE FOR INFLUENZA A VIRAL ANTIGEN',
      'POSITIVE FOR PARAINFLUENZA TYPE 1',
      'POSITIVE FOR PARAINFLUENZA TYPE 3',
      'POSITIVE FOR PARAINFLUENZA VIRUS',
      'POSITIVE FOR RESPIRATORY SYNCYTIAL VIRUS (RSV)',
      'RESPIRATORY SYNCYTIAL VIRUS (RSV)',
      'VARICELLA-ZOSTER VIRUS',
      'RHINOVIRUS',
      'VIRUS' ) THEN 'Viral'
      WHEN me.ORG_NAME IN ( 'ACREMONIUM SPECIES', 'ASPERGILLUS FUMIGATUS', 'ASPERGILLUS NIGER', 'ASPERGILLUS SP. NOT FUMIGATUS, FLAVUS OR NIGER', 'ASPERGILLUS SPECIES', 'ASPERGILLUS USTUS', 'ASPERGILLUS VERSICOLOR GROUP', 'aspergillus versicolor', 'BASIDIOMYCETE', 'CANDIDA (TORULOPSIS) GLABRATA', 'CANDIDA ALBICANS', 'CANDIDA ALBICANS, PRESUMPTIVE IDENTIFICATION', 'CANDIDA DUBLIENSIS', 'CANDIDA DUBLINIENSIS', 'CANDIDA GUILLIERMONDII', 'CANDIDA KEFYR', 'CANDIDA KRUSEI', 'CANDIDA LUSITANIAE', 'CANDIDA PARAPSILOSIS', 'CANDIDA SPECIES', 'CANDIDA TROPICALIS', 'CLADOSPORIUM SPECIES', 'CURVULARIA SP.', 'DEMATIACEOUS MOLD', 'EXOPHIALA JEANSELMEI', '%FUNGUS%', 'FUSARIUM SPECIES', 'GEOTRICHIUM SPECIES', 'GEOTRICHUM CAPITATUM', 'HISTOPLASMA CAPSULATUM', 'MALASSEZIA SPECIES', 'MOLD', 'MUCOR SP.', 'MYCELIA STERILIA', 'PAECILOMYCES SPECIES', 'PENICILLIUM SPECIES', 'POSITIVE FOR PNEUMOCYSTIS CARINII', 'POSITIVE FOR PNEUMOCYSTIS JIROVECII (CARINII)', 'RHIZOPUS SPECIES', 'SACCHAROMYCES CEREVISIAE', 'SCEDOSPORIUM APIOSPERMUM', 'STACHYBOTRYS SPP.', 'STEMPHYLIUM SP.', 'SYNCEPHALASTRUM SPECIES', 'TRICHOPHYTON SPECIES', 'TRICHOSPORON ASAHII', 'YEAST', 'YEAST, PRESUMPTIVELY NOT C. ALBICANS', 'fungus', 'aspergillus' ) THEN 'Funghi'
      WHEN me.ORG_NAME IN ( 'ENTAMOEBA HARTMANNI',
      'ENDOLIMAX NANA',
      'FEW BLASTOCYSTIS HOMINIS',
      'GIARDIA LAMBLIA',
      'GIARDIA LAMBLIA SEEN',
      'TAENIA SP.',
      'MODERATE BLASTOCYSTIS HOMINIS' ) THEN 'Parasite'
    ELSE
    'Negative'
  END
    AS CLASSIFIED
  FROM
    step1 AS me
  GROUP BY
    me.SUBJECT_ID,
    me.HADM_ID,
    me.ICUSTAY_ID,
    me.SPEC_TYPE_DESC,
    me.ORG_NAME
  ORDER BY
    me.SUBJECT_ID,
    me.HADM_ID,
    me.SPEC_TYPE_DESC,
    me.ORG_NAME)
SELECT
  coho.SUBJECT_ID,
  coho.ICUSTAY_ID,
  coho.HADM_ID,
  coho.SPEC_TYPE_DESC,
  coho.ORG_NAME,
  coho.Classified
FROM
  classifiedGroup AS coho
WHERE
  coho.Classified = 'Negative'
  #where coho.ORG_NAME = '2ND ISOLATE'
  #where coho.classified = 'Negative' and coho.ORG_NAME is not null
ORDER BY
  coho.SUBJECT_ID;

-- delete second isolated microbiology test results
#select count(distinct(subject_id)) from `mimic-267216.CohorSelection_Pneumonia.3_SelectCultureNegative`  as c ;
#select *
#from  `mimic-267216.CohorSelection_Pneumonia.3_SelectCultureNegative` as c where c.Classified = 'Negative' and c.ORG_NAME is not null;
#delete from  `mimic-267216.CohorSelection_Pneumonia.3_SelectCultureNegative` as c 
#where c.Classified = 'Negative' and c.ORG_NAME is not null;